name: build

on:
  workflow_call:
  
jobs:
  build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Docker login
              uses: docker/login-action@v3.3.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v3.8.0

            - name: Build and push Docker images
              uses: docker/build-push-action@v6.11.0
              with:
                context: .
                push: true
                tags: production
                target: ${{ secrets.DOCKER_USERNAME }}/jornadamilhas:latest

          