name: build

on:
  workflow_call:
  
jobs:
  
  build-container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # - name: Docker login
            #   uses: docker/login-action@v3.3.0
            #   with:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Docker Setup Buildx
            #   uses: docker/setup-buildx-action@v3.8.0

            # - name: Build and push Docker images
            #   uses: docker/build-push-action@v6.11.0
            #   with:
            #     context: .
            #     push: true
            #     target: production
            #     tags: ${{ secrets.DOCKER_USERNAME }}/jornadamilhas:latest

  deploy:
        runs-on: ubuntu-latest
        needs: [build-container]
        
        steps:
            - uses: actions/checkout@v4

            - name: Deploy
              # Only run this step if the main branch
              if: github.ref == 'refs/heads/main'
              run: |
                curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

        