name: Tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
    unit-test:
        
        name: Unit Tests
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
       
            - name: Install dependencies
              run: npm ci --include=dev
            
            - name: Run tests
              run: npm test

    integration-test:
        name: Integration Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'

            - name: Copy .env file
              env: 
                HASH_SALT: ${{ secrets.HASH_SALT }}
              run: |
                cp .env.example .env.test
                echo "HASH_SALT=$HASH_SALT" >> .env.test
                cat .env.test

            - name: Install dependencies
              run: npm ci --include=dev

            - name: Run tests
              run: npm run test:e2e
