name: tests

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
    unit-test:
        
        name: Unit Tests
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
       
            - name: Install dependencies
              run: npm ci --include=dev
            
            - name: Run tests
              run: npm test

    integration-test:
        name: Integration Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'

            - name: Copy .env file
              run: cp .env.example .env

            - name: Install dependencies
              run: npm ci --include=dev

            - name: Run tests
              run: npm run test:e2e

    build:
        name: Build and Deploy
        needs: [unit-test, integration-test]
        uses: ./.github/workflows/build-deploy.yml
        secrets: inherit
